spring:
  application:
    name: cinema

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
